[phases.setup]
nixPkgs = ["python310", "gcc", "python310Packages.pip", "python310Packages.setuptools", "python310Packages.wheel", "bash"]

[phases.install]
cmds = ["bash ./test_env.sh && bash ./install.sh"]

[phases.build]
cmds = []

[start]
cmd = "bash ./start.sh" 